'''
euler_002.py
Second problem of the Euler Project

------------------------------------------------------------------------------
Each new term in the Fibonacci sequence is generated by adding the previous two 
terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
------------------------------------------------------------------------------

Written by Stephen Outten 21 December 2017
'''

import numpy as np
import fibonacci as fib

nmax = 4000000
fibarray = fib.fib_seq_nmax(nmax)  
fibarray = fibarray[fibarray/2 == fibarray//2] 
answer = np.sum(fibarray)

print('The sum of all the even Fibonacci numbers less than %i is %i' % (nmax,answer))

